def warehouse_daily_with_zscore() -> str:
    return """
SELECT
    WAREHOUSE_NAME,
    DATE(START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS DAILY_CREDITS,
    AVG(SUM(CREDITS_USED)) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY DATE(START_TIME)
        ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
    ) AS ROLLING_AVG,
    STDDEV(SUM(CREDITS_USED)) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY DATE(START_TIME)
        ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
    ) AS ROLLING_STDDEV,
    CASE
        WHEN STDDEV(SUM(CREDITS_USED)) OVER (
            PARTITION BY WAREHOUSE_NAME
            ORDER BY DATE(START_TIME)
            ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
        ) = 0 THEN 0
        ELSE (
            SUM(CREDITS_USED) - AVG(SUM(CREDITS_USED)) OVER (
                PARTITION BY WAREHOUSE_NAME
                ORDER BY DATE(START_TIME)
                ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
            )
        ) / STDDEV(SUM(CREDITS_USED)) OVER (
            PARTITION BY WAREHOUSE_NAME
            ORDER BY DATE(START_TIME)
            ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
        )
    END AS Z_SCORE
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE DATE(START_TIME) BETWEEN %s AND %s
GROUP BY WAREHOUSE_NAME, DATE(START_TIME)
ORDER BY WAREHOUSE_NAME, USAGE_DATE
"""
